### ISSUE TITLE
Pull request #21 can cause problems

### ISSUE THREAD

**Issue by pilotak** [adafruit/Adafruit_MCP9808_Library#23]
I don't think calling `_wire->begin();` in `::init()` is a good idea in PR #21 . Lets say on ESP8266 you can remap I2C pins and specify different speed so you init the I2C object outside this class and you pass on as reference.

```cpp
Adafruit_MCP9808 mcp;

void setup() {
    Wire.begin(SDA_2, SCL_2);
    Wire.setClock(400000);

    mcp.begin(&Wire);
}
````
I think that  `_wire->begin()` should be only in `::begin()` and  `::begin(uint8_t addr)`

**Comment by ladyada** [comment]
hiya we don't want to break how eveything works, the way you'd do this in ESP is to define a Wire object in the BSP for your pins. maybe you can ask ESP to add a setPins() funciton isntead of overloading begin!
