### ISSUE TITLE
Identical temperature readings for highest resolution mode with wake()

### ISSUE THREAD

**Issue by jlunz** [adafruit/Adafruit_MCP9808_Library#26]
Longer delay in Adafruit_MCP9808::wake() for for highest resolution mode / slowest temperature conversion time needed?

https://github.com/adafruit/Adafruit_MCP9808_Library/blob/4f2b2d938fe23705626923140f9a8f5a3a135458/Adafruit_MCP9808.cpp#L175-L178

I have the following setup:
``` c
Adafruit_MCP9808 mcp_internal = Adafruit_MCP9808();
void setup() {
  if (!mcp_internal.begin(0x19)) {
    Serial.println("Couldn't find MCP9808! Check your connections and verify the address is correct.");
  }
  mcp_internal.setResolution(3);
}

void loop() {
  mcp_internal.wake();
  float c = mcp_internal.readTempC();
  mcp_internal.shutdown(); 
  Serial.print(c, 4); Serial.println("*C");
}
```
Tried on Seeduino 4.2 and DIY-Arduino (8 MHz internal clock).

With **delay(250)** I get the same reading every time:
```
27.6250*C
27.6250*C
27.6250*C
...
```

Increasing the delay to values greater than 250 and I am seeing all measurements as expected.
The datasheet only states a Typical conversion time of 250 ms for the highest resolution, so this might not be enough in my case.

Not using the wake() function and calling shutdown_wake(false) + delay of course works, though a first-time user might be surprised.

**Comment by ladyada** [comment]
sure you can submit a PR for a longer delay or a configurable delay?

**Comment by jlunz** [comment]
Sure!
