### ISSUE TITLE
shutdown_wake(0) can put the device in shutdown mode

### ISSUE THREAD

**Issue by bbx10** [adafruit/Adafruit_MCP9808_Library#7]
If the device is not in shutdown mode and shutdown_wake(0) is done, the function sets the shutdown bit to a 1 which puts the chip in shutdown mode. In other words, it has the opposite effect.

``` cpp
  tempsensor.shutdown_wake(0);
```

``` cpp
int Adafruit_MCP9808::shutdown_wake( uint8_t sw_ID )

    if (sw_ID == 0)
     {
-       conf_shutdown = conf_register ^ MCP9808_REG_CONFIG_SHUTDOWN ;
+       conf_shutdown = conf_register & ~MCP9808_REG_CONFIG_SHUTDOWN ;
```

The current code toggles the shutdown bit using XOR instead of zeroing the bit.

**Comment by ladyada** [comment]
fixed
